### ISSUE TITLE
32位的树莓派感觉被放弃了

### ISSUE THREAD

**Issue by wucangeo** [SpringHgui/FastTunnel.SuiDao#1]
==
-_-

**Comment by SpringHgui** [comment]
这个主要看微软是否支持了，只要能运行.net core5的环境，都可以的。

运行时环境地址：
https://dotnet.microsoft.com/download/dotnet/5.0

你下载对应的版本运行时，如果运行时可以运行，那就没问题

**Comment by wucangeo** [comment]
明白了，好像并不能成功。
多谢回复。 @SpringHgui
